### ISSUE TITLE
General loading pattern

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#100]
Design and implement a general "loading wheel" or similar pattern, covering the whole screen while important things load.  

## Expected behavior
- [ ] Show the loading pattern in the  Campaign, WG and Proposal Dashboard,

**Comment by thiagodemellobueno** [comment]
Allow me to recommend
http://github.hubspot.com/pace/docs/welcome/

https://raw.githubusercontent.com/bgryszko/react-native-circular-progress/master/screenshot.gif

**Comment by cdparra** [comment]
Moved back to "in progress". PACE loader does not play well with WebSokets

**Comment by cdparra** [comment]
Fixed by adding the following at the very beginning of appcivist_ui_core
```javascript
 window.paceOptions = {
    ajax: false,
    restartOnRequestAfter: false,
    document: false, // disabled
    eventLag: false, // disabled
    elements : {
      selectors: [".appmain"] // limiting selector to control to appmain
    }
  };
```
