### ISSUE TITLE
Notifications settings under profile settings 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#115]
![image](https://user-images.githubusercontent.com/630150/28298345-c0dd4d70-6b40-11e7-8a11-a4b7542f377e.png)

Create a partial for the user settings page including notification settins

**Comment by rafaelangarita** [comment]
@cdparra You must use the [checkbox plugin](https://developers.facebook.com/docs/messenger-platform/plugin-reference/checkbox-plugin) for Facebook Messenger.

I have already implemented this to see how it works. You can find it in views/sendToMessenger.ejs [here](https://gitlab.inria.fr/usnb/facebook-bc-bot-appcivist)

I can work closely with the person implementing this if you want.

**Comment by cdparra** [comment]
@jorgeramirez and @gvescu will be working on this. I assigning this issue to next week sprint.
