### ISSUE TITLE
Campaign voting: voting results modal 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#137]
![image](https://user-images.githubusercontent.com/630150/30272383-474b0f80-96c2-11e7-9c3a-00f4cf775e2b.png)

**Comment by gvescu** [comment]
@cdparra Does this one referrs to the Current Voting Status mockup on #139's PDF?

**Comment by cdparra** [comment]
@gvescu Yes! Added the mockup in the issue description.
