### ISSUE TITLE
Design and Implement Display voting controls for consensus voting on the Working Group Dashboard

### ISSUE THREAD

**Issue by pablodefendini** [socialappslab/appcivist-patterns#16]
Design the consensus visualisation and buttons for the Working Group Pages. Members of the WG must be able to cast their votes on their proposals to decide which are going to continue and which are going to be excluded.

Add consensus voting capabilities to the Working Group Dashboard template. Possibly adding...
- Voting buttons
- Archival administration buttons on the Consensus page

Template: http://patterns.littlemacondo.com/?p=templates-working-group-dashboard

Early design: https://slack-files.com/T0GH49XJ5-F2K89C1QA-fe2dcfd537

## Definition of Done

- [ ] When loading up [the template](http://patterns.littlemacondo.com/?p=templates-working-group-dashboard), we should see...
  - [ ] Voting Buttons
  - [ ] Voting Results

**Comment by RobLoach** [comment]
Possible a "Show Results" button that pops down the current results?

![screenshot at 2016-11-28 12-10-51](https://cloud.githubusercontent.com/assets/25086/20678167/bdf459ca-b563-11e6-9376-a5bbddbad0ca.png)

**Comment by cdparra** [comment]
Notes for Consensus and Informal Voting

- [ ] Informal Voting #97 
    1. Display results as a +/- difference
    2. Show  the number of Thumbs Up/Down when hovering over the Thumbps Up/Down icons
        - https://github.com/socialappslab/appcivist-patterns/issues/97 -- @RobLoach
    3. Whether to enable informal voting or not is a decision that coordinators can make in the campaign menu

- [ ] WG Consensus https://github.com/socialappslab/appcivist-patterns/issues/98
   1. The coordinator starts the process from the WG Contextual Menu, choosing the voting system. 
   2. When consensus starts, Thumbs Up/Down icons are replaced by Voting Controls
   3. Voting Systems we need to support: 
      1. Range: each proposal can be scored between a MIN and MAX score. The final result is ranked by the average of scores received by each proposal
      2. Ranked: members of the group rank the proposals per order of preference. The final resulta is the aggregated ranking. 
      3. Plurality: members of the group mark proposals with YES, NO, ABSTAIN and BLOCK. The aggregated number of yes, no, abstain and blocks on each proposal are used to rank the proposals (by diff of yes/no, below a threshold of blocking and requiring certain number of votes to count)  
      4. Distribution: members of the group distribute a number of points among proposals. The final resulta is the aggregated ranking.  
- [ ] Consensus Results: #99
      1. Design how the results look like for each voting system (e.g., pie chart for plurality, etc.)
      2. Design where and how to see the results
         1. when hovering over voting controls
         2. on the top of all the proposals
         3. in the WG Header 
      3. Design how the coordinator can act upon results
          1. Have a menu item to select all proposals under certain score or threshold and then exclude
          2. ...

Old designs for each different voting System: 

## Range Voting

**Voting Controls:**
![image](https://cloud.githubusercontent.com/assets/630150/20781318/d22dae26-b736-11e6-9bfa-e39e5a6a5bfc.png)

**Results:**
![image](https://cloud.githubusercontent.com/assets/630150/20781337/eb6f5b78-b736-11e6-9bbd-72382e1bfcea.png)

## Plurality Voting

**Voting Controls:**
![image](https://cloud.githubusercontent.com/assets/630150/20781346/fdcbad08-b736-11e6-87bb-ef35c09e1fba.png)

**Results:**
![image](https://cloud.githubusercontent.com/assets/630150/20781372/249fc374-b737-11e6-9cf9-673b508cc4d5.png)

## Ranked Voting 
**Voting Controls:**
![image](https://cloud.githubusercontent.com/assets/630150/20781410/5a334fce-b737-11e6-88ad-668b3e9cce9b.png)

**Results:**
![image](https://cloud.githubusercontent.com/assets/630150/20781419/6a005e92-b737-11e6-865a-68e1a6fe63a0.png)

## Distribution Voting (elements same as range)
**Voting Controls:** 
![image](https://cloud.githubusercontent.com/assets/630150/20781380/30d64a00-b737-11e6-855a-1227813864b8.png)

**Results:**
![image](https://cloud.githubusercontent.com/assets/630150/20781392/44f90b12-b737-11e6-9f2a-367437567361.png)

**Comment by RobLoach** [comment]
This epic is split into a few different stories, all linked above. While this EPIC is not part of the sprint, one of its related tasks is.
