### ISSUE TITLE
Produce a Moodboard

### ISSUE THREAD

**Issue by andrewmallis** [socialappslab/appcivist-patterns#33]
We compile a palette of found colors, fonts, photography and illustration styles, and other imagery that explores a visual identity for AppCivist. We use a moodboard to suss out the “look and feel” of a brand with a you, contrast it with your competitors’ visual identity, and hone in on an approved visual identity system.

## Definition of done
Moodboard iterations towards acceptance by PO

**Comment by thiagodemellobueno** [comment]
@cdparra – here is some background on moodboards

UX and Moodboards
http://gibbon.co/c/3789b393-6306-4e8f-b150-3253f8e23b7f/how-a-web-design-mood-board-impacts-user-experienc

A little case study incorporating moodboards.
http://thoughtmerchants.com/customer-io/

### And a bunch of examples:
- http://jasonbeaty.com/imgs/projects/gb/boardedit.jpg
- https://static1.squarespace.com/static/520554b9e4b04f935ee79ed1/t/539e200de4b014e1736c383d/1402871824711/
- http://racheljue.com/img/moodBoard1-dtBook.png
- https://d13yacurqjgara.cloudfront.net/users/58708/screenshots/1799154/moodboard.png
- http://maplekuo.com/wp-content/uploads/2015/05/qup_moodboard.jpg
- http://alexychang.com/assets/img/projects/MoodBoard.png

**Comment by thiagodemellobueno** [comment]
Here's the moodboard. 
We've already moved on to the next step, which is the design language, but want to present that in person on Monday's meeting.

https://projects.invisionapp.com/boards/862ZEAQEADBJ3/
