### ISSUE TITLE
Improve build stability and performance through grunt-sass

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#35]
The current build process uses [grunt-contrib-sass](https://www.npmjs.com/package/grunt-contrib-sass), which uses Ruby to compile the SASS. Switching to [grunt-sass](https://www.npmjs.com/package/grunt-sass) will improve performance and stability, as it uses [libsass](http://libsass.org/) instead. Will allow building the system with or without Ruby installed locally.

## Definition of Done

1. Can build the system without Ruby installed
2. The result should be the same as what it was when using `grunt-contrib-sass`

## QA

1. Review https://github.com/socialappslab/appcivist-patterns/pull/58 and test to make sure it's working
3. Re-build the site and make sure it still looks the same
2. Merge it

**Comment by thiagodemellobueno** [comment]
Gulp!

**Comment by andrewmallis** [comment]
@cdparra not sure if you saw this issue yet.
We don't like Ruby. It is very messy to manage for teams, and is slow.

@RobLoach is there perhaps an upstream patternlab fix that can be looked at, here? We don't want to fork such a big project too heavily.

**Comment by cdparra** [comment]
We discussed this during the standup meeting @andrewmallis. I suggested we keep it on the backlog and work on it if there is time. It would be a plus, but is not an urgent matter at the moment

**Comment by cdparra** [comment]
Maybe @jorgeramirez can also provide some input on this (though, as I said before, it is of no urgency now)

**Comment by RobLoach** [comment]
@andrewmallis 

> is there perhaps an upstream patternlab fix that can be looked at, here? We don't want to fork such a big project too heavily.

The upstream ([`edition-node-grunt`](https://github.com/pattern-lab/edition-node-grunt)) doesn't use SASS. It's something that appcivist-patterns adds to allow compiling the SASS components. This is purely on the appcivist-patterns side, no upstream conflicts.

For some history, Pablo added it in https://github.com/socialappslab/appcivist-patterns/commit/360ca8f85d0bc702bc84bbd21626b1b9d3148875 . While grunt-contrib-sass is good, grunt-sass is better.

**Comment by cdparra** [comment]
@RobLoach there are two more things that depend on ruby in this implementation: [`susy`](http://susy.oddbird.net/) and [`compass`](http://compass-style.org/)

**Comment by RobLoach** [comment]
Thanks @cdparra. Added those as dependencies so that they're brought in.
