### ISSUE TITLE
Consider design patterns for separation of Ideas VS Proposals

### ISSUE THREAD

**Issue by thiagodemellobueno** [socialappslab/appcivist-patterns#36]
Quick sketch session with Cristhian and Thiago around arranging proposals/ideas.

Thiago will flesh this story out a bit to align with goals.

- Quick Sketches
- Figure out what the differences are?
- What's the workflow?

**Comment by RobLoach** [comment]
James mentioned Ideas/Proposals separation was quite clear in the Invision.
https://projects.invisionapp.com/d/main#/console/9543264/205023328/build

Last slide.

**Comment by cdparra** [comment]
We have reviewed the design of the Ideas column and both James and I agree that we like it as a way of differentiating ideas from proposals. It would be good to see this in combination with the first screen, which contains the color scheme that we liked best.
