### ISSUE TITLE
Design search bars for ideas/proposal views

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#39]
Add the Search abilities to the Proposals templates. It is an open search by keywords (title/text).

**Comment by RobLoach** [comment]
We have to remove the "Theme" from the cards/search bar. It's already being displayed from the filter tool. There is a comment in Invision.

**Comment by cdparra** [comment]
We have reviewed again and agree with the comments already made during the review meeting. Let's move these designs to actual patterns.

**Comment by thiagodemellobueno** [comment]
![screen shot 2016-11-15 at 1 06 07 pm](https://cloud.githubusercontent.com/assets/79221/20317503/542568ec-ab34-11e6-81dd-3ec0cf6f6c7a.png)
