### ISSUE TITLE
Implement Prototype to Sort by name, most recent and popularity/votes

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#41]
On the Proposals/Ideas board, we want the ability to sort by a few different things:

- [ ] Name
- [ ] Most Recent
- [ ] Popularity/Votes

Template: https://projects.invisionapp.com/d/main#/console/9543264/205023329/preview

## Definition of Done

1. On the Proposals board, you should see the ability to sort by...
  - Name
  - Date
  - Popularity

**Comment by thiagodemellobueno** [comment]
Not to forget "random"
