### ISSUE TITLE
Design Screen for the Add New Proposal/Idea Form

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#43]
Design the Add New Proposal/Ideas Form from scratch.

Proposal Template: Campaign Dashboard at http://patterns.littlemacondo.com/?p=templates-campaign-dashboard

Button link to Add New Proposal will appear in the Proposals section in:
http://patterns.littlemacondo.com/?p=templates-campaign-dashboard

### Fields
- Authors
- Working Group
- Title
- Description
- Category/Tags
- Source Code (external provided ID - text field)
- On Proposal, the following fields also exist (Proposal toggle)
  - Proposal Text (title, summary, ID of ideas bundled in this proposal, category, authoring working group, feedback)" (metadata)
    - Summaries of proposals from Etherpad
    - http://patterns.littlemacondo.com/?p=templates-single-proposal

## Definition of Done

- [ ] There is a design put together for the Add New Proposal and Idea Forms.

**Comment by RobLoach** [comment]
@cdparra to provide an example and description of the fields.

**Comment by cdparra** [comment]
Here is the model for Ideas

``` json
{
  "title": "string",
  "text": "string",
  "type": "IDEA",
  "lang": "en-US",
  "sourceCode" : "1234",
  "themes": [
    {
      "themeId": 66
    }
  ],
  "attachments": [
    {
      "url": "string",
      "resourceType": "'PROPOSAL', 'PICTURE', 'VIDEO', 'PAD', 'TEXT', 'WEBPAGE', 'FILE', 'AUDIO', 'CONTRIBUTION_TEMPLATE'",
      "name": "string",
      "title": "string",
      "description": "string",
      "readOnlyPadId": "string",
      "urlLargeString": "string",
      "urlMediumString": "string",
      "urlThumbnailString": "string"
    }
  ],
  "hashtags": [
    {
      "hashtagId": 55
    },
    {
      "hashtag": "water"
    }
  ],
  "authors" : [ 
    {
      "userId": 99
    }
   ],
  "nonMemberAuthor": {
    "name": "string",
    "email": "string",
    "url": "string"
  },
  "location": {
    "placeName": "string",
    "street": "string",
    "city": "string",
    "state": "string",
    "zip": "string",
    "country": "string",
    "geoJson": "string"
  }
```

And here is the model for proposals

``` json
{
  "title": "string",
  "text": "string",
  "type": "PROPOSAL",
  "lang": "en-US",
  "sourceCode" : "12345", 
  "themes": [
    {
      "themeId": 66
    }
  ],
  "attachments": [
    {
      "url": "string",
      "resourceType": "'PROPOSAL', 'PICTURE', 'VIDEO', 'PAD', 'TEXT', 'WEBPAGE', 'FILE', 'AUDIO', 'CONTRIBUTION_TEMPLATE'",
      "name": "string",
      "title": "string",
      "description": "string",
      "readOnlyPadId": "string",
      "urlLargeString": "string",
      "urlMediumString": "string",
      "urlThumbnailString": "string"
    }
  ],
  "hashtags": [
    {
      "hashtagId": 55
    },
    {
      "hashtag": "water"
    }
  ],
  "location": {
    "placeName": "string",
    "street": "string",
    "city": "string",
    "state": "string",
    "zip": "string",
    "country": "string",
    "geoJson": "string"
  },
  "status": "NEW",
  "workingGroupAuthors": [
    {
      "groupId": 0
    }
  ],
  "associatedIdeas" : [{"contributionId":1}, {"contributionId":2}, {"contributionId":3}], 
  "extendedTextPad": {
    "url": "string",
    "resourceType": "PAD",
    "name": "string",
    "title": "string",
    "description": "string",
    "readOnlyPadId": "string"
  }
}
```

Some notes: 
- Anything that is accessible via an URL can be an attachment
- In the array of Themes, ID must refer to an existing theme in the campaign, so this list is provided
- In the array of Hashtags (which is used for informal keywords), including the ID refers to an existing hashtag, not including creates a new. 
- In proposals, the extendedTextPad is not needed on creation, this is created and made available when the proposal is submitted. 
- Ideas have individual authors (who are users in the system) but not a working group. An idea can also contain a non member author (i.e., the author has no user in the system)
