### ISSUE TITLE
Design the Add New Proposal/Ideas Form from scratch and by import from a CSV

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#44]
Design the Add New Proposal/Ideas Form: from scratch or by upload/import from a CSV (e.g., drag and drop) 

This is an epic that tackles the 2nd row of https://docs.google.com/spreadsheets/d/1JBlV28gIKsgX6zv_wDVbazNnwNwd5S8ocmk4Ur8dzbk/edit#gid=668416790 .

**Comment by cdparra** [comment]
Add language to make it clear that uploading means uploading more than one
