### ISSUE TITLE
Design the Visualization of Contribution History - Initial Investigation

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#45]
Template: http://patterns.littlemacondo.com/?p=templates-campaign-dashboard-no-ideas
Anonymous Campaign Dashboard
Working Group Dashboard

Create a User Interface around http://www.jsoneditoronline.org/?id=762e6711874dd01a2dd87d89070e2435 , mainly the "changes" section.
``` json
  {
    "creation": "2016-10-19 05:59 AM GMT",
    "lastUpdate": "2016-10-19 05:59 AM GMT",
    "lang": "en",
    "removal": null,
    "removed": false,
    "contextUserId": null,
    "contributionHistoryId": 7,
    "contributionId": 71,
    "uuid": "ebda5585-e465-451f-a7f2-81a8c24a9110",
    "title": "New idea chekcing history",
    "text": "New idea for history",
    "type": "BRAINSTORMING",
    "moderationComment": null,
    "budget": null,
    "actionDueDate": null,
    "actionDone": false,
    "action": null,
    "assessmentSummary": null,
    "authors": [],
    "changes": {
      "internalChanges": [
        "title"
      ],
      "externalChanges": [
        {
          "externalRef": "authors",
          "externalRefId": 1,
          "changeType": "DELETED"
        }
      ],
      "associationChanges": [
        {
          "resourceSpaceId": 94,
          "type": "CAMPAIGN",
          "changeType": "ADDED"
        }
      ]
    }
  }
```

## Definition of Done

- [ ] We have a demonstration of how contribution history could be seen

**Comment by RobLoach** [comment]
@cdparra mentioned he can provide some better examples as well.

**Comment by thiagodemellobueno** [comment]
@cdparra yeah, we need a slightly more comprehensive example.

Additionally, are any specific changes more or less prominent than others, etc?

**Comment by RobLoach** [comment]
@cdparra to provide a sketch on the history visualization.

**Comment by cdparra** [comment]
First rough sketch: 
![image](https://cloud.githubusercontent.com/assets/630150/20548404/0a254100-b0d8-11e6-8a4b-80d6ded0a114.png)

**Comment by cdparra** [comment]
Second sketch: 

![image](https://cloud.githubusercontent.com/assets/630150/20574155/0998f2c8-b168-11e6-88ed-460c4eff868b.png)

Notes: 
- I tried to exemplify the three types of changes we are tracking: 
![image](https://cloud.githubusercontent.com/assets/630150/20574110/dbbab88c-b167-11e6-84fb-46de6cbcd44e.png) Changes in the content of the Idea/proposal (called internal in the JSON example)

![image](https://cloud.githubusercontent.com/assets/630150/20574201/38fcbee6-b168-11e6-9721-330fadea5a23.png) New external items added to/removed from the Proposal/Idea (called external in the JSON example)

![image](https://cloud.githubusercontent.com/assets/630150/20574230/52c1be44-b168-11e6-881c-29b9588fe550.png) Associations of the Idea/Proposal to other spaces of collaboration (called associations in the JSON example)

**Comment by thiagodemellobueno** [comment]
I like it, 
Can you elaborate on the large prominent rectangles?

If those are mostly just labels, i say that we let it be a header. I will take a visual pass at this now so we can discuss a little further.

**Comment by thiagodemellobueno** [comment]
Question, what object is this attached to? is it specifically a "Campaign contribution history" or is it "Proposal/Idea" contribution history" .. will we have both?

There just seems to be a bit of an overlap in the example.

**Comment by thiagodemellobueno** [comment]
And most importantly, what do people click where to get to this?

**Comment by cdparra** [comment]
@thiagodemellobueno answers below: 
1. the rectangles are just a quick way of expressing that it would be nice to have some form of "snapshot" (i.e., summary of its contents) of the item that is being referenced int he "history item". It does not necessarily have to be a that rectangle, I am sure there are better ways of showing that

2. Histories are attached to Ideas and Proposals (which are both "Contributions" internally). Probably, best not to use the word contribution and be specific saying that it is "Idea history". 

3. In the context menu of each card, there is a "History" item.

**Comment by thiagodemellobueno** [comment]
Gotcha, here's a visual pass.

I'm envisioning it being a modal.

![screen shot 2016-11-25 at 12 39 40 pm](https://cloud.githubusercontent.com/assets/79221/20632543/47080e8c-b30c-11e6-8881-221af59c38b8.png)


Snapshots: so like when google used to show a full page preview on hover? Or is it more like linking to a vew the item in question with the content from that period?

**Comment by cdparra** [comment]
Snapshots: now that I see your design, I see that basic information about the changes and the entity we are referencing is already inline and that's probably much better than showing an snapshot (which probably would be complicated to do). I am inclining to drop the snapshot idea

**Comment by thiagodemellobueno** [comment]
👍

**Comment by thiagodemellobueno** [comment]
We may need to add links to the comments.

Moving to prototyping.

**Comment by RobLoach** [comment]
Just missing the icons. Easy fix.
