### ISSUE TITLE
Elaborate on Tag/Filter Mechanism

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#47]
Adding a mechanism to Add new Tags/Themes on the filter Proposal component. Be able to Select different tags when you click on the Filter.

**Comment by cdparra** [comment]
@thiagodemellobueno A minor issue: the button in the Add filters modal is shown as follows

![image](https://cloud.githubusercontent.com/assets/630150/20574344/d293f970-b168-11e6-9112-ad3386c31e5c.png)

**Comment by thiagodemellobueno** [comment]
@cdparra ready for qa anew.

![screen shot 2016-11-23 at 3 02 17 pm](https://cloud.githubusercontent.com/assets/79221/20576913/dab05ce6-b18d-11e6-9029-7614ce1af757.png)
