### ISSUE TITLE
Design how ideas get incorporated into proposals

### ISSUE THREAD

**Issue by thiagodemellobueno** [socialappslab/appcivist-patterns#53]
Design the "Promote to Idea" functionality. You should be able to select more then one idea, and have a way to port it to a Proposal. Be able to mass-select Ideas, and Promote them to all become Proposals.

## Acceptance Criteria

- There is a bulk operation menu to opening a new proposal form and converting the Ideas to Proposals
- When you click on Promote, you get the New Idea form with the old Idea information already in there.

**Comment by thiagodemellobueno** [comment]
![screen shot 2016-11-23 at 12 03 14 am](https://cloud.githubusercontent.com/assets/79221/20551624/467aa3d8-b110-11e6-8561-b316542121d0.png)

**Comment by cdparra** [comment]
@thiagodemellobueno looks great to me. One minor question though: although I like the effect of the cog and select icon appearing when hovering on proposals, I wonder if that would be a problem for non-tech-savvy users who will interact with the platform? 
 
As for the rest, everything looks perfect to me in this design 

BTW, I moved this to **In progress**

**Comment by thiagodemellobueno** [comment]
I'm happy to remove the hover behavior.

I'm a believer that users engage and discover to a certain degree, specially for "non essesntial functions" and that the cognitive load of cluttered interfaces outweighs the need for users to engage in a little 'discovring' where they learn a system.

That is to say, if users will have access to some of this functionality immediately in the "single proposal" page, then we benefit from not cluttering the interface, so long as it's clear and obvious

Hovering over "a thing you want to act on" is pretty intuitive behavior. 
And then you get an icon... oh whats that? let's click it.

This is particularly true of software people are going to use with some frequency.
Which is to say, most people using your system will be using this more than once, and their understanding of how the app works will grow over time. 

Invision uses this pattern successfuly (understood that their audience maybe has a higher fluency of interaction) : 

![screen shot 2016-11-25 at 10 26 30 am](https://cloud.githubusercontent.com/assets/79221/20629465/b264527a-b2f9-11e6-9d7d-c80a27f94614.png)


Another question is will the non tech-savvy users (those that use the software casually vs someone who has some familiarity / training / purpose in using the platform)  use the contextual menu?
If they do, is there something for them to do there? (I only see some sort of "report" functionality being relevant to them).

**Comment by cdparra** [comment]
We discussed with James and decided to keep the hovering interaction and test with users
