### ISSUE TITLE
add sass to the patternlab tasks in the gruntfile

### ISSUE THREAD

**Issue by pablodefendini** [socialappslab/appcivist-patterns#6]
Not quite sure how to best make Sass into an automated process to run as part of [patternlab:serve](https://github.com/socialappslab/appcivist-patterns/blob/master/Gruntfile.js#L156). Currently, I've added sass to the project, but I have to run sass separately from the other patternlab grunt tasks (my grunt experience is very limited). @jorgeramirez can you take a look?

**Comment by jorgeramirez** [comment]
@pablodefendini I'll take a look into this!

**Comment by jorgeramirez** [comment]
@pablodefendini Just pushed the feature branch related to this issue. Now when you do grunt patternlab:serve it automatically compiles assets on the fly.

**Comment by pablodefendini** [comment]
it looks like it includes compass as well—is that correct? If so, I'll go ahead and attempt a merge.

**Comment by jorgeramirez** [comment]
The grunt-contrib-sass assumes that sass is already installed.

**Comment by pablodefendini** [comment]
This works as expected: `grunt patternlab:serve` and everything just lights up.
