### ISSUE TITLE
Viewing Anonymous Templates

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#64]
Create templates for viewing anonymous content.

Template:
http://patterns.littlemacondo.com/?p=templates-anonymous-campaign-dashboard

Anonymous Users able to see...

- History
- Commenting

## Acceptance Criteria

1. On the Prototype, you should be able to use the same templates for both Anonymous, and Logged in
2. Show the Template with the controls, and highlight the ones that would not be shown to Anonymous users

**Comment by RobLoach** [comment]
Anonymous View doesn't have open/close nav.

**Comment by cdparra** [comment]
Heads up: I added the anonymous navigation template in two templates that needed it
- Anonymous Campaign Dashboard
- Anonymous All Proposals View
