### ISSUE TITLE
Style the Navigation Contents

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#65]
Style all the navigation elements to match Invision.

## Acceptance Criteria

- The navigation controls are styled
- The nav are equal to the designs in the InvisionApp
- Invision: https://projects.invisionapp.com/d/main#/console/9543264/205023333/comments

**Comment by cdparra** [comment]
@thiagodemellobueno is this the final color for the links or is a preliminary option? 
![image](https://cloud.githubusercontent.com/assets/630150/20574401/166573e0-b169-11e6-9675-5b9af7498d36.png)

**Comment by thiagodemellobueno** [comment]
Styled up the links.

Can we create a separate issue for adding the login / user blocks into the nav.

Thanks!

**Comment by cdparra** [comment]
Done, new issue is #73 (with a minor bonus ;-) )
