### ISSUE TITLE
Implement the Sub/Context Menus

### ISSUE THREAD

**Issue by RobLoach** [socialappslab/appcivist-patterns#66]
Work on the Sub/Context. Should be in the Ideas and Proposal cards.

## Acceptance Criteria

- Edit (authors)
- Publish (coordinators of authoring working group)
- Evaluate (Use to be Give Feedback) (managers/authoring working group member)
- Exclude (managers/authoring working group coordinators)
- History (everyone)
- Assign (managers)
- Promote to Proposal (managers/authors/working group members)
- Close (everyone)

## Template
https://projects.invisionapp.com/d/main#/console/9543264/204265764/preview

![context](https://cloud.githubusercontent.com/assets/25086/20494723/4b682b10-afec-11e6-90c2-f8e7ba38e832.png)

**Comment by RobLoach** [comment]
@thiagodemellobueno suggested bringing the contextual menu to the Idea/Proposal page itself rather then on the card.

**Comment by thiagodemellobueno** [comment]
Propsal Card
Idea Card
Campaign header
Proposal header
User Header
Working Group Header
Single Proposal Header
