### ISSUE TITLE
Fix styling problems

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#69]
Revise and fix the styling in the Single Proposal Template and Working Group Dashboard

## Problems

1. Some section titles are on top of each other

**Single Proposal**

![image](https://cloud.githubusercontent.com/assets/630150/20496394/d941f65e-afd9-11e6-9f6e-f585ab34458f.png)

** Working Group Dashboard**
![image](https://cloud.githubusercontent.com/assets/630150/20496645/e50ab25e-afda-11e6-9b41-adb68743eabd.png)

2. AppCivist Logo appears in big at the bottom of the page. This is part of the footer, and should only appear there. 
![image](https://cloud.githubusercontent.com/assets/630150/20496465/1bdd30c8-afda-11e6-9f35-95617f9f7f05.png)

## Acceptance Criteria
- [ ] Each of the listed problems are fixed

**Comment by RobLoach** [comment]
`?p=templates/caampaign-dashboard`

**Comment by cdparra** [comment]
@thiagodemellobueno the working group dashboard still has the overlapping titles problem
![image](https://cloud.githubusercontent.com/assets/630150/20574553/de61f74c-b169-11e6-95b4-018a63370a23.png)

**Comment by thiagodemellobueno** [comment]
@cdparra can we make an issue specifically for the working group dashboard please?

**Comment by cdparra** [comment]
Done, new issue is #72
