### ISSUE TITLE
Implement user patterns in the navigation component

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#73]
Add the login / signup / user blocks into the nav

## Acceptance criteria
1. [ ] Login/Signup links appear in anonymous version of the nav
2. [x] User profile pic + name + settings link + log out link appear in the non-anonymous version
3. [ ] BONUS fix the minor misalignment between section titles and section contents in the nav (see pic below) 

![image](https://cloud.githubusercontent.com/assets/630150/20578125/8e907232-b17a-11e6-833d-1a9573e0229f.png)

**Comment by thiagodemellobueno** [comment]
I want to keep "anonymous stuff" in the "anonymous " ticket.
