### ISSUE TITLE
Implement icons in idea and proposal listing headers

### ISSUE THREAD

**Issue by thiagodemellobueno** [socialappslab/appcivist-patterns#74]
The proposal and idea listing headers need a little love.
But its sort of not mega critical.

Template: http://patterns.littlemacondo.com/?p=templates-campaign-dashboard

**Comment by RobLoach** [comment]
![screenshot at 2016-11-28 12-21-22](https://cloud.githubusercontent.com/assets/25086/20678565/31286ebc-b565-11e6-8938-7a8056146389.png)
