### ISSUE TITLE
Elevate Single proposal to redesign

### ISSUE THREAD

**Issue by thiagodemellobueno** [socialappslab/appcivist-patterns#76]
Applying new design to proposal single

Template: http://patterns.littlemacondo.com/?p=templates-single-proposal

Voting up/down fixes and contextual menu fix.

**Comment by RobLoach** [comment]
Small things to do on the Vote Up/Down.

**Comment by thiagodemellobueno** [comment]
Move voting module to below "long form description."

**Comment by RobLoach** [comment]
- Navigation
- Vote Up Down on the Single Proposal
