### ISSUE TITLE
Decide on interactions and permissions of Informal Voting on Ideas/Proposals for Working Groups

### ISSUE THREAD

**Issue by thiagodemellobueno** [socialappslab/appcivist-patterns#81]
Lots of conversation surrounded the informal voting mechanisms, and @cdparra and @jamesholston were going to deliberate.

**Comment by thiagodemellobueno** [comment]
![screen shot 2016-11-25 at 2 34 23 pm](https://cloud.githubusercontent.com/assets/79221/20634343/ce95a164-b31d-11e6-9dd4-19ea72af3e54.png)


Not to lead the witnesses, but here's a little riff on some of the things @jamesholston was discussing.

**Comment by cdparra** [comment]
* Display results as a +/- difference
* Show the number of Thumbs Up/Down when hovering over the Thumbps Up/Down icons
* Whether to enable informal voting or not is a decision that coordinators can make in the campaign menu
