### ISSUE TITLE
Fix/improve styling and language issues

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#85]
Based on some general comments after going through the templates: 

- [x] Add some more space between the actions for proposals and ideas in the campaign template (between "See All" and "Add New", it is hard to see what the separation is). Same happens with In the ideas column where "See All", "Add New” and “Hide Ideas” are cramped and each word read as  a different action. Each action should be clearly a unit
- [x] Removed the language “By” or “In the” and have only a visually distinctive way of showing the names of Working Groups in the proposal/ideas cards and the single proposal page. 
- [x] Cleanup proposal cards responsiveness: overlapping content with voting controls
![image](https://cloud.githubusercontent.com/assets/630150/20637487/849e7a06-b33e-11e6-8956-6bfd5ca0dfc4.png)
- [x] In pagination molecules, change “Prev” to “Previous” 

## Acceptance criteria
- [x] All issues have been addressed

**Comment by RobLoach** [comment]
> Removed the language “By” or “In the” and have only a visually distinctive way of showing the names of Working Groups in the proposal/ideas cards and the single proposal page.

![screenshot at 2016-11-28 12-24-34](https://cloud.githubusercontent.com/assets/25086/20678691/a86d9de4-b565-11e6-99d6-dd11d3cf629e.png)
![screenshot at 2016-11-28 12-24-57](https://cloud.githubusercontent.com/assets/25086/20678702/afc9baaa-b565-11e6-962b-1fbee5f1d88f.png)

> Cleanup proposal cards responsiveness: overlapping content with voting controls

![screenshot at 2016-11-28 12-25-28](https://cloud.githubusercontent.com/assets/25086/20678725/c6c4c088-b565-11e6-8755-e1c0f29a549c.png)

**Comment by cdparra** [comment]
I know this was not included, but there is an issue on how the contextual menu is seen in the ideas cards: 
![image](https://cloud.githubusercontent.com/assets/630150/21059299/9b283268-bdf6-11e6-85c7-80d393460e05.png)
