### ISSUE TITLE
Make the AppCivist brand more prominent

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#86]
By showing the name on each page, making it visually prominent or differentiated somehow

Some ideas: 
- make search box to read “Search AppCivist…”
- include powered by AppCivist in each header as in example below
![2b1fbe16-c861-4815-8880-7958567dab02](https://cloud.githubusercontent.com/assets/630150/20637503/fd45a75e-b33e-11e6-8be0-4d6061df70f0.png)

**Comment by RobLoach** [comment]
Those two are suggestions, but we could improve it somehow else. Possibly using the Logo? Watermark?
