### ISSUE TITLE
Implement Contribution History Design Pattern

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#88]
Following the design in #45, implement needed patterns

## Acceptance Criteria

- [ ] Contribution History Patterns is available in the Campaign Dashboard, after clicking the menu item "History" on proposal/ideas cards

**Comment by RobLoach** [comment]
Just missing the icons. Easy fix.

**Comment by thiagodemellobueno** [comment]
![screen shot 2016-11-30 at 4 45 24 pm](https://cloud.githubusercontent.com/assets/79221/20772677/7054f57a-b71c-11e6-9bc4-6331a488a637.png)
