### ISSUE TITLE
Implement consensus voting configuration as a modal in working group.

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#93]
- [ ] START/FINISH consensus for coordinators
   * Should open a modal to configure consensus: select voting system, some key values to be filled by front-end
   * Finish should archive the results  
- [ ] See archived results
   * A modal window with the same voting results design patterns that will come up from #96

**Comment by RobLoach** [comment]
Talk about this one tomorrow? Wasn't originally part of this Sprint.

**Comment by cdparra** [comment]
Sure! Since it was put on "QA" by @thiagodemellobueno, I thought it was done and hence the comments. But maybe something was misunderstood.

**Comment by RobLoach** [comment]
:+1:  Doing extra stuff is always good!

**Comment by thiagodemellobueno** [comment]
I was a bit confused about what this one meant ;)
