### ISSUE TITLE
Design and implement Consensus Voting Results

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#96]
Following instructions in #16

**Comment by thiagodemellobueno** [comment]
Show current state, pop up a modal with:

- [ ] pie
- [ ] how you voted
- [ ] percentage of people that have responded so far.

**Comment by thiagodemellobueno** [comment]
Pie chart, using data attributes http://www.chartjs.org/ 
(we did this in Eecs in the prototype of "for the numbers" using data-tags and it was straightforward. That work should mean we can get this story in with the time we have.

**Comment by cdparra** [comment]
@thiagodemellobueno how complicated would it be to include an averaged display of the consensus results in the working group consensus? 

At the end of the consensus process, we could see something like this, in the WG dashboard, with a menu item being to "Show/Display Last Consensus Results"  (picture from the alpha prototype): 

![image](https://cloud.githubusercontent.com/assets/630150/21059188/1fd50a82-bdf6-11e6-87a1-9404c4122394.png)
