### ISSUE TITLE
Implement patterns for Informal Voting

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#97]
Follow instructions in #16 

- Display results as a +/- difference
- Show the number of Thumbs Up/Down when hovering over the Thumbps Up/Down icons
- Whether to enable informal voting or not is a decision that coordinators can make in the campaign menu

**Comment by cdparra** [comment]
Informal Voting

Display results as a +/- difference
Show the number of Thumbs Up/Down when hovering over the Thumbps Up/Down icons
Whether to enable informal voting or not is a decision that coordinators can make in the campaign menu

**Comment by cdparra** [comment]
The only missing thing is the +/- difference @thiagodemellobueno (as you originally included, but with either + or - depending on the dff)

**Comment by thiagodemellobueno** [comment]
Sorry i don't understand what you mean?

**Comment by cdparra** [comment]
I meant having this (originally posted in #81 as part of the early discussion on this): 
![image](https://cloud.githubusercontent.com/assets/630150/21024894/1add8646-bd3b-11e6-9515-b8d8e59efee7.png)

The 32 here could be “+32” if there are 32 more likes and dislikes, and viceversa (like reddit, and no need of the "people liked this" explanation on the side, we want to experiment and see what do thes users do with this information)

to give a bit more of context, the discussion with James was that this is going to be "configurable". Both Assemblies and Working Groups will have the chance of enabling/disabling informal voting
